[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[cursor]
  [cursor.style]
  shape = "Beam"
  blinking= "On"
  [cursor.vi_mode_style]
  shape = "Block"
  blinking= "Off"


