-- require("nvchad.configs.lspconfig").defaults()
--
-- local servers = { "html", "cssls" }
-- vim.lsp.enable(servers)
--
-- local util = require "lspconfig/util"
--
-- -- Go
-- vim.lsp.config.gopls.setup {
--   cmd = { "gopls" },
--   filetypes = { "go", "gomod", "gowork", "gotmpl" },
--   root_dir = util.root_pattern("go.work", "go.mod", ".git"),
--   settings = {
--     gopls = {
--       completeUnimported = true,
--       usePlaceholders = true,
--       analyses = {
--         unusedparams = true,
--       },
--     },
--   },
-- }
--
-- -- TypeScript / JavaScript
-- vim.lsp.config.tsserver.setup {
--   init_options = {
--     preferences = {
--       disableSuggestions = true,
--     },
--   },
-- }
--
-- -- TOML
-- vim.lsp.config.taplo.setup {}

-- require("nvchad.configs.lspconfig").defaults()
--
-- vim.lsp.enable({
--     "html",
--     "cssls",
--     "jsonls",
--     "taplo",
--     "vtsls",
--     "marksman",
--     "pylsp",
--     "gopls",
-- })

--
-- -- Optional: override gopls settings
-- vim.lsp.config.gopls.setup({
--   settings = {
--     gopls = {
--       completeUnimported = true,
--       usePlaceholders = true,
--       analyses = { unusedparams = true },
--     },
--   },
-- })
--
-- -- Optional: tweak tsserver
-- vim.lsp.config.vtsls.setup({
--   init_options = { preferences = { disableSuggestions = true } },
-- })
