#!/usr/bin/env bash

set -e

# --- Helper Functions --- #
script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

# --- Dotfile Management --- #
log "--------- dev-env ---------"

cd "$script_dir"

copy_dir() {
    pushd "$1"
    to="$2"
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf "$to/$dir"
        execute cp -r "$dir" "$to/$dir"
    done
    popd
}

copy_file() {
    from="$1"
    to="$2"
    name=$(basename "$from")
    execute rm -f "$to/$name"
    execute cp "$from" "$to/$name"
}

# --- Main Logic --- #

# --- Symlink .zshrc --- #
if [ ! -L "$HOME/.zshrc" ]; then
  log "Creating .zshrc symlink..."
  execute rm -f "$HOME/.zshrc"
  execute ln -s "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
else
  log ".zshrc symlink already exists."
fi

# --- Symlink tms --- #
if [ ! -L "/usr/local/bin/tms" ]; then
  log "Creating tms symlink..."
  execute mkdir -p "$HOME/.local/bin"
  execute ln -sf "$HOME/.config/tmux/sessionizer/tms" "/usr/local/bin/tms"
else
  log "tms symlink already exists."
fi
