#!/usr/bin/env bash

set -e

# --- Configuration --- #
REPO_URL="https://github.com/vivindeena/config.git"
CONFIG_DIR="$HOME/.config"

# --- Helper Functions --- #
log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

# --- Remote Execution --- #
if [ ! -d "$CONFIG_DIR/.git" ]; then
    echo "Cloning dotfiles repository..."
    git clone "$REPO_URL" "$CONFIG_DIR"
    cd "$CONFIG_DIR"
    echo "Running setup..."
    ./run
    exit 0
fi

# --- Main Logic --- #
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
filter=""
dry="0"

cd "$script_dir"
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f)

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log "run: filter=$filter"

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "filtered: $filter -- $script"
        continue
    fi
    log "running script: $script"
    execute "./$script"
done

