#!/usr/bin/env bash

set -e

source "$(dirname "${BASH_SOURCE[0]}")/../scripts/os-detect.sh"

if [[ "$OS" == "macOS" ]]; then
  install neovim
elif [[ "$OS" == "Arch" ]]; then
  # You might need to adjust the package name for Arch if it's different
  install neovim
fi
