#!/usr/bin/env bash

set -e

# This check is to avoid running this script if bat is not installed
if ! command -v bat &> /dev/null; then
    echo "bat not found, skipping theme setup."
    exit 0
fi

theme_dir="$(bat --config-dir)/themes"
theme_file="$theme_dir/Catppuccin Mocha.tmTheme"

mkdir -p "$theme_dir"

if [ ! -f "$theme_file" ]; then
  echo "Installing Catppuccin Mocha for bat..."
  curl -fsSL \
    https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme \
    -o "$theme_file"
else
  echo "Catppuccin Mocha for bat is already installed."
fi

bat cache --build
