#!/usr/bin/env bash

set -e

export BUN_INSTALL="$HOME/.bun"
if [ ! -s "$BUN_INSTALL/bin/bun" ]; then
  echo "Installing bun..."
  curl -fsSL https://bun.sh/install | bash
else
  echo "bun already installed."
fi