#!/usr/bin/env bash

set -e

export NVM_DIR="$HOME/.nvm"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
fi

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

if ! nvm list | grep -q "lts/"; then
  echo "Installing latest LTS version of Node.js..."
  nvm install --lts
  nvm alias default 'lts/*'
else
  echo "Latest LTS version of Node.js already installed."
fi
