#!/usr/bin/env bash

set -e

# --- Symlink .zshrc --- #
if [ ! -L "$HOME/.zshrc" ]; then
  echo "Creating .zshrc symlink..."
  rm -f "$HOME/.zshrc"
  ln -s "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
else
  echo ".zshrc symlink already exists."
fi

# --- Symlink tms --- #
if [ ! -L "/usr/local/bin/tms" ]; then
  echo "Creating tms symlink..."
  mkdir -p "$HOME/.local/bin"
  ln -sf "$HOME/.config/tmux/sessionizer/tms" "/usr/local/bin/tms"
else
  echo "tms symlink already exists."
fi
