# --- General --- #
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# --- Keybindings --- #
# Set prefix to C-a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Split panes with | and -
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Reload config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Resize pane sizes
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5
bind -r m resize-pane -Z

# Kill the current session: auto-switch if only 1 other session, otherwise show list
bind X run-shell "~/.config/tmux/scripts/switch-and-kill.sh"

bind-key "t" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# --- Window and Pane Management --- #
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Ensure window titles get renamed automatically.
setw -g automatic-rename

# Make new windows inherit cwd instead of $HOME
# set-option -g default-path "#{pane_current_path}" # DEPRECATED
unbind C
bind C new-window -c "#{pane_current_path}"

# --- Clipboard and Copy Mode --- #
#set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

# unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# --- History --- #
# Memory optimization for scrollback buffer
set-option -g history-limit 1000

# --- Plugins --- #
# TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

# Catppuccin Mocha theme configuration
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
# set -g @catppuccin_window_text ' → #T'
# set -g @catppuccin_window_current_text ' → #T'
set -g @catppuccin_user_text ' #{user}'
set -g @catppuccin_date_time_text ' %a %-d %b, %Y, %-I:%M%p'
# set -g status-left-length 100
# set -g status-right-length 100
set -g status-left '#{tmux_mode_indicator}#{E:@catppuccin_status_session}'
set -g status-right '#{E:@catppuccin_status_user}'
set -ag status-right '#{E:@catppuccin_status_date_time}'

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
